# use mysql 
FROM mysql:5.7

# set environment variables
ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=ubid
ENV MYSQL_ALLOW_EMPTY_PASSWORD=yes

# expose the mysql port
EXPOSE 3306

# copy SQL script to initialize database
COPY ubid.sql /docker-entrypoint-initdb.d/ubid.sql
