# Use the official MySQL image
FROM mysql:5.7

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=ubid

# Expose MySQL port
EXPOSE 3306

# Copy SQL script to initialize database
COPY Docker/ubid.sql /docker-entrypoint-initdb.d/ubid.sql